name: NodeJS application continuous integration

on:
  pull_request:
  push:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  pre_commit_hook:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - id: cache-nodejs
        uses: actions/cache@v3
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-nodejs-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: npm ci --include=dev

      - name: Check CI
        run: npm run pre-commit
